services:
  asciidoc_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: asciidoc_img:latest
    container_name: asciidoc_container
    # NOTE: localに成果物を共有するためにvolumeマウントしている
    volumes:
      - ./:/app
