# Dev Containerではこちらが優先される。
services:
  asciidoc_app:
    build:
      target: devcontainer
      context: ./
      dockerfile: Dockerfile
    image: asciidoc_devcontainer:latest
    container_name: asciidoc_devcontainer_container
    volumes:
      - ./:/app # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。

